[package]
name = "gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.2"
image = "0.24.9"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
